import os

#os.system("python -m pm4py.cli DiscoverPetriNetAlpha tests\\input_data prova2")
#os.system("python -m pm4py.cli DiscoverPetriNetInductive tests\\input_data prova2")
#os.system("python -m pm4py.cli DiscoverPetriNetHeuristics tests\\input_data prova2")
#os.system("python -m pm4py.cli DiscoverBPMNInductive tests\\input_data prova2")
#os.system("python -m pm4py.cli DiscoverProcessTreeInductive tests\\input_data prova2")
#os.system("python -m pm4py.cli ConformanceDiagnosticsTBR tests\\input_data\\running-example.xes tests\\input_data\\running-example.pnml result_diagnostics_tbr.txt")
#os.system("python -m pm4py.cli ConformanceDiagnosticsAlignments tests\\input_data\\running-example.xes tests\\input_data\\running-example.pnml result_diagnostics_alignments.txt")
#os.system("python -m pm4py.cli FitnessTBR tests\\input_data\\running-example.xes tests\\input_data\\running-example.pnml result_fitness_tbr.txt")
#os.system("python -m pm4py.cli FitnessAlignments tests\\input_data\\running-example.xes tests\\input_data\\running-example.pnml result_fitness_alignments.txt")
#os.system("python -m pm4py.cli PrecisionTBR tests\\input_data\\running-example.xes tests\\input_data\\running-example.pnml result_precision_tbr.txt")
#os.system("python -m pm4py.cli PrecisionAlignments tests\\input_data\\running-example.xes tests\\input_data\\running-example.pnml result_precision_alignments.txt")
#os.system("python -m pm4py.cli ConvertToXES tests\\input_data\\running-example.csv result_ru.xes")
#os.system("python -m pm4py.cli ConvertToCSV tests\\input_data\\running-example.xes result_ru.csv")
#os.system("python -m pm4py.cli ConvertPNMLtoBPMN tests\\input_data\\running-example.pnml result_bpmn1.bpmn")
#os.system("python -m pm4py.cli ConvertPNMLtoPTML tests\\input_data\\running-example.pnml result_ptml1.ptml")
#os.system("python -m pm4py.cli ConvertPTMLtoPNML tests\\input_data\\running-example.ptml result_pnml1.pnml")
#os.system("python -m pm4py.cli ConvertPTMLtoBPMN tests\\input_data\\running-example.ptml result_bpmn2.bpmn")
#os.system("python -m pm4py.cli ConvertBPMNtoPNML tests\\input_data\\running-example.bpmn result_pnml3.pnml")
#os.system("python -m pm4py.cli ConvertDFGtoPNML tests\\input_data\\running-example.dfg result_pnml4.pnml")
#os.system("python -m pm4py.cli DiscoverDFG tests\\input_data\\running-example.xes result_dfgdisc.dfg")
#os.system("python -m pm4py.cli ConvertDFGtoPNML result_dfgdisc.dfg result_dfgdisc_conv.pnml")
#os.system("python -m pm4py.cli SaveVisDFG result_dfgdisc.dfg visual_dfg.png")
#os.system("python -m pm4py.cli SaveVisPNML result_pnml1.pnml visual_petri.png")
#os.system("python -m pm4py.cli SaveVisBPMN result_bpmn1.bpmn visual_bpmn.png")
#os.system("python -m pm4py.cli SaveVisPTML result_ptml1.ptml visual_process_tree.png")
os.system("python -m pm4py.cli SaveVisDottedChart tests\\input_data\\running-example.xes time:timestamp case:concept:name concept:name vis_dotted.png")
os.system("python -m pm4py.cli SaveVisTransitionSystem tests\\input_data\\running-example.xes vis_trans_system.png")
os.system("python -m pm4py.cli SaveVisTrie tests\\input_data\\running-example.xes vis_trie.png")
os.system("python -m pm4py.cli SaveVisEventsDistribution tests\\input_data\\running-example.xes days_week vis_ev_distr.png")
os.system("python -m pm4py.cli SaveVisEventsPerTime tests\\input_data\\running-example.xes vis_ev_time.png")
