VIEW_MULTI_SET = 'multiset'
VIEW_SET = 'set'
VIEW_SEQUENCE = 'sequence'

VIEWS = {VIEW_MULTI_SET, VIEW_SET, VIEW_SEQUENCE}

DIRECTION_FORWARD = 'forward'
DIRECTION_BACKWARD = 'backward'
DIRECTIONS = {DIRECTION_FORWARD, DIRECTION_BACKWARD}

PARAM_KEY_VIEW = 'view'
PARAM_KEY_WINDOW = 'window'
PARAM_KEY_DIRECTION = 'direction'
# DEFAULT_PARAMETERS = {PARAM_KEY_VIEW: VIEW_MULTI_SET, PARAM_KEY_WINDOW: 5, PARAM_KEY_DIRECTION: DIRECTION_FORWARD}
DEFAULT_PARAMETERS = {PARAM_KEY_VIEW: VIEW_SEQUENCE, PARAM_KEY_WINDOW: 2, PARAM_KEY_DIRECTION: DIRECTION_FORWARD}
